### ISSUE TITLE
日本語訳を追加してもらえないでしょうか？

### ISSUE THREAD

**Issue by nakayoshisandayo** [manabox/simple-membership-japanese#1]
以下の英文に対する日本語訳を追加してもらえないでしょうか？

「
This content is not permitted for your membership level.
」

**Comment by manabox** [comment]
Readmeにも記述のとおり、一部翻訳対象となっていないテキストもあります。これらはプラグイン制作側の方で翻訳対象テキストに指定されていないので、こちらからは元ファイルを変更しない限り翻訳ファイルを作成できないんです。お役に立てずすみません(´ε｀；)

**Comment by nakayoshisandayo** [comment]
なるほど。了解です。
ありがとうございました。（＾＾）
